apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-app.fullname" . }}-backend
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: {{ include "fullstack-app.fullname" . }}-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
