apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-app.fullname" . }}-frontend
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "fullstack-app.fullname" . }}-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
